
name: release

on:
  push:
    branches:
      main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: read version
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./widget.json
          property: version

      - name: Release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          with:
            tag_name: v${{steps.version.outputs.value}}
            release_name: v${{steps.version.outputs.value}}
            body: Release v${{steps.version.outputs.value}}
            draft: false
            prerelease: false
